### ISSUE TITLE
Chromebook crashes when I close the lid

### ISSUE THREAD

**Issue by ktechmidas** [duffydack/linux-max98090#5]
Hi,

Interestingly only happens on this kernel, but when I close the lid and open it later the chromebook (Toshiba Chromebook 2)  starts up new. last reports a crash... any way I can find out what's crashing it?

monotoko tty7         :0               Fri Oct 20 13:38 - crash  (00:00)

**Comment by duffydack** [comment]
It's an issue I've tried to source already (see the other issue on here).  I had the problem when I used Seabios (RW Legacy), but after I flashed the UEFI rom from Mrchromebox (I recommend you do) suspend works perfectly.  I'd like to know what's causing it, as I've looked at everything related to intel/power/acpi.  Maybe making the sound work is what's causing it, I dunno.

**Comment by duffydack** [comment]
Could you test this 4.14 kernel (with minimal config changes) to see if it resolves the problem.  If it works then you can also test my normal config with 4.14, and I can go from there.  As i said tho, UEFI fixes it 🤷‍♂️

**Comment by ktechmidas** [comment]
Hey! Sorry it took me so long to test, busy weekend...  

This one actually works well, no issues with suspend and sound still works. What config did you remove from the kernel?

**Comment by duffydack** [comment]
This is what's baffling me.  I've diff'ed till blue in the face and I can't see anything related to acpi, video, EC, gpio, apm etc that would affect it.  I'd like you to try 4.14 with my stripped down config to see if it's a 4.13 problem, same link https://drive.google.com/drive/folders/0B_M5BSg_FZkxbmtEQmR5TmFUWFE?usp=sharing

If it doesn't work then at least I know what DOES work and use that in future.
