### ISSUE TITLE
Suggestion: Make a built for GalliumOS

### ISSUE THREAD

**Issue by Jimster121** [duffydack/linux-max98090#6]
Hello,

Can you please create the appropriate driver for GalliumOS Baytrail devices? Here is the issue: https://github.com/GalliumOS/galliumos-distro/issues/180. Although the Toshiba CB30-B-104 seems to be fixed, the ASUS C300 Chromebook (my device) still has sound problems. I have the latest GalliumOS updates and Full ROM update installed.

- Thank you

**Comment by duffydack** [comment]
Welcome to the baytrail linux clusterfuck.  Gallium isn't something I have time or interest in, sorry.
Anyway, what audio issue exactly, no audio or distorted when using duplex (output+input)?  You should have sound, but as far as distortions with duplex, there's nothing I can do about that.  Thank the kernel devs for a sloppy workaround to get sound working in kernels above 4.5

**Comment by Jimster121** [comment]
I have distored sound and use duplex, as I told you before I use the latest version which I think is 4.18? Do you have a recommendation?

**Comment by duffydack** [comment]
The distortion with duplex has been around forever, and I will only get fixed I think when the kernel devs update this device to use the newer *trail driver.  Right now it's still having to use the old driver which can only be compiled into kernel by disabling the newer driver(s).  The whole situation is a clusterfuck, but, it might get better since they've acknowledged the issue and merged the patches needed for 4.9+ to get sound working into 4.13, but it's still just a quick fix just to get sound output working.  The only suggestion I can give you is if you have removed write protect and flashed the 'full rom', then you may as well flash UEFI, it's a bit better overall - not for sound particularly, but worth using anyway.  BTW latest stable kernel is 4.13, and gallium uses 4.8 I believe (why they don't use 4.9 which is LTS I'll never understand).
One other suggestion if it matters, if you only use output (speakers or headset) - no mic input, just output, then you can fix the distortion that happens sometimes after inserting headphones by using pavucontrol and selecting the profile to use Stereo Output only.  That's all I got for now..

**Comment by Jimster121** [comment]
Okay thank you for this information. So, the only thing I can do is wait for a newer driver to be released. :disappointed:

**Comment by duffydack** [comment]
Nothing you can do other than use older LTS kernel like 4.1.  Don't hold you breath for a kernel fix.

I can see kernel 4.4 in the gallium/ubuntu repo, so you could try installing that, it was the last version before the newer cherrytrail driver came into play that borked our hardware.  No idea if inputs ever worked properly.

You could also just buy https://www.amazon.co.uk/s/ref=nb_sb_noss/257-7842757-8663011?url=search-alias%3Daps&field-keywords=TROND+AC2+Aluminum+USB+Audio+Adapter

no idea if it works.

**Comment by Jimster121** [comment]
Okay, switching to a different kernel seems to be the best solution, how can I do that exactly? I found some images here http://apt.galliumos.org/pool/main/l/linux-upstream/. Will it wipe my data?

**Comment by duffydack** [comment]
You can try, it won't wipe your install, just install another kernel to choose from boot menu.   download 
linux-firmware-image-4.1.14-galliumos_30_amd64.deb
linux-image-4.1.14-galliumos_30_amd64.deb
linux-headers-4.1.14-galliumos_30_amd64.deb
then sudo dpkg -i *.deb
I've not used ubuntu based distro for a while, but that should work.

**Comment by Jimster121** [comment]
I downloaded and installed the .deb files with no errors. When I restarted it still booted from 4.8. How can I make it boot from 4.1 instead of 4.8? Is there a file I have to change?

**Comment by duffydack** [comment]
I'd have thought it would trigger grub update..  might need a sudo update-grub
if that doesn't work then try sudo grub-mkconfig -o /boot/grub/grub.cfg

**Comment by Jimster121** [comment]
It didn't work 😞

**Comment by Jimster121** [comment]
This may help you https://www.reddit.com/r/GalliumOS/comments/59nak0/squawks_bay_trail_bytmax98090_kernel_no_sound/

**Comment by duffydack** [comment]
help me?  I don't need any help lol

**Comment by Jimster121** [comment]
just sent you sth relevant I found  on google 😉

**Comment by duffydack** [comment]
It's not relevant because the kernel used in gallium is old.  I only handle the most recent kernel.
what didn't work?  didn't install the old kernel, didn't update grub, didn't have sound??

**Comment by Jimster121** [comment]
I installed the new kernel: 
`jimmy@asusc300:~$ sudo update-grub
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.8.17-galliumos
Found initrd image: /boot/initrd.img-4.8.17-galliumos
Found linux image: /boot/vmlinuz-4.1.14-galliumos
Found initrd image: /boot/initrd.img-4.1.14-galliumos
Adding boot menu entry for EFI firmware configuration
done`
When I boot: `Linux version 4.8.17-galliumos (reynhout@galliumos) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #1 SMP PREEMPT galliumos4`

**Comment by duffydack** [comment]
You need to choose it then from grub menu.  If there is no menu you press (i think) escape before grub boots kernel

**Comment by Jimster121** [comment]
Pressing Esc will open the boot menu, is there a way to make grub options show up at startup? Can I remove the new kernel and only use the old one?

**Comment by duffydack** [comment]
https://askubuntu.com/a/16049

**Comment by Jimster121** [comment]
I saw that issue before but I was not sure if it would work or destroy the installation, I'll give it a try.

**Comment by Jimster121** [comment]
Didn't work, should I remove the new kernel and only use the old one?

**Comment by duffydack** [comment]
Does the old kernel work?

**Comment by Jimster121** [comment]
I don't know, it should be, it didn't show any errors

**Comment by duffydack** [comment]
You should know if
It installed
It booted
It had working sound/mic

**Comment by Jimster121** [comment]
Then, I don't know I'll open up a new issue on the GalliumOS repository (I think it is called like this) and ask them about changing kernels

**Comment by duffydack** [comment]
If you don't mind losing your gallium install, you can try something out with me....

**Comment by Jimster121** [comment]
Ok, tell me

**Comment by duffydack** [comment]
hit me up on hangouts and I'll walk you through it (a little)
duffydack73@gmail.com

**Comment by Jimster121** [comment]
Can't do through email?

**Comment by duffydack** [comment]
back and forth over email when you'll have a lot of questions is gonna be a pain in the ass.
Forget that then for now.. I was going to give you my personal iso (archlinux) to install and test with my kernel.. I'll update the iso so you don't have to install anything, just boot it as you would any other livecd.
What apps do you use with microphone?

**Comment by Jimster121** [comment]
So you are saying that I should get your personal .iso file and install ArchLinux? I don't thik that I am capable of using ArchLinux.

**Comment by duffydack** [comment]
I'm saying you won't have to install it. Just write it to usb stick and boot it, same as you would with gallium

**Comment by Jimster121** [comment]
Ok and then install it and use it from now on, in order to have sound/mic?

**Comment by duffydack** [comment]
If you wanted, but it may not be necessary, if I can verify the change in my kernel works it may work in gallium (for gallium guys to implement)

**Comment by Jimster121** [comment]
Ok, nice but for the time being, I will wait for a while until I get an answer from GalliumOS forums.

**Comment by duffydack** [comment]
so what app do you use with the mic?

**Comment by Jimster121** [comment]
I use Skype

**Comment by duffydack** [comment]
*ugh,ffs...*   ok then I'll get someone else I know to test.  It's in no way a 'fix', but the garbled distortion happens for a split second and recovers itself quick enough to be good enough to call a fix... as good as we're gonna get for now.

**Comment by Jimster121** [comment]
Good Luck!

**Comment by Jimster121** [comment]
Hey, remember me? I found the solution here https://www.reddit.com/r/GalliumOS/comments/7aphlp/comment/dpyczso Thank you so much for your support :D

**Comment by duffydack** [comment]
On 17-11-17, Jimster121 wrote:
> Hey, remember me? I found the solution here https://www.reddit.com/r/GalliumOS/comments/7aphlp/comment/dpyczso Thank you so much for your support :D
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/duffydack/linux-max98090/issues/6#issuecomment-345346889


Ok, cool.  So you are using 4.1?

-- 
Dean

**Comment by Jimster121** [comment]
Yes

**Comment by duffydack** [comment]
And it's 100% working sound?

**Comment by Jimster121** [comment]
Seems to be ok
