### ISSUE TITLE
linux-git-max98090 version 4.14rc8.r0.g39dae59d66ac-1 breaks suspend again

### ISSUE THREAD

**Issue by Jasperro** [duffydack/linux-max98090#7]
I upgraded to linux-git-max98090 version 4.14rc8.r0.g39dae59d66ac-1 today, rebooted and to my surprise suspend was broken again. 4.14rc7 worked fine, had no problems. I also cleaned my pacman package cache, so I can't revert. I also can't find any logs that may be helpful. (Device: Gnawty 1.0 - CB3-111)

**Comment by duffydack** [comment]
I wanted to test something, seems I have my answer.  I'll have it sorted in an hour or so.

**Comment by Jasperro** [comment]
Thanks. And yes, I'm using seabios.

**Comment by duffydack** [comment]
Yes it's not an issue for UEFI.  Updated, should be back to normal now.
